### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by sohailb108** [ellensp/gcode-thumbnailer#1]
Since ANTIALIAS was removed in Pillow 10.0.0, it should be changed to LANCZOS in line 78.

`scaled = pixbuf.resize((int(width),int(height)), Image.ANTIALIAS)`

Should become:

`scaled = pixbuf.resize((int(width),int(height)), Image.LANCZOS)`

**Comment by ellensp** [comment]
Time is the great destroyer, this includes code apparently.

Updated.
